### ISSUE TITLE
Add support to validate node under seed.

### ISSUE THREAD

**Issue by Skaapdev** [waxtatect/basic_machines#9]
@waxtatect 

Longstanding bug, mover does not validate which nodes seeds are planted on. The end result is seeds are planted in mid air and on top of nodes that are not soil. It also wasting those seeds that should have gone to a valid dirt location as they aren't returned. Not a big issue for most games, but almost a deal breaker for my game.

My solution is to check a list of `valid soils` before placing a seed. Feel free to use PR: https://github.com/waxtatect/basic_machines/pull/8 or ignore/modify as you see fit.

Disclaimer: I have *not* tested all seeds at this point in time. So I may still need to add to the `valid soils` list.

I tested planting cactus and large cactus seedlings and they seem to avoid this check altogether and are planted as normal
So i don't see this breaking trees or anything else.

Disclaimer: I have *only* tested with farming redo.

**Comment by waxtatect** [comment]
See https://github.com/waxtatect/basic_machines/pull/8
